homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: 'reminders'

automation:
  - alias: REM - Kaffet 채r klart
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.kaffebryggare
      to: 'on'
      for:
        minutes: 5
    action:
      - service: notify.ios_thomas_iphone
        data:
          title: "Fikadax!"
          message: "Kaffet 채r f채rdigt!"
  - alias: REM - St채ng av kaffebryggaren
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.kaffebryggare
      to: 'on'
      for:
        minutes: 15
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.kaffebryggare
